[package]
name = "microphaser"
version = "0.1.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]

[dependencies]
bio = "*"
rust-htslib = { git = "https://github.com/rust-bio/rust-htslib", branch="master" }
clap = { version = "2.27", features = ["yaml", "color", "suggestions"]}
itertools = "0.6"
log = "0.3"
vec_map = "0.8"
